2023-11-14 13:15:39 Main.py              Connect_btn_clicked            INFO     Line:41   visa address: GPIB0::11::INSTR
2023-11-14 13:15:40 Main.py              Connect_btn_clicked            ERROR    Line:57   Connect to Instrument fail!!!
2023-11-14 13:16:39 Main.py              Read_btn_clicked               ERROR    Line:74   Read respond Fail!!!
2023-11-14 13:16:41 Main.py              Query_btn_clicked              ERROR    Line:87   Can't query command: 
2023-11-14 13:16:49 Model.py             Write_commands_from_file       ERROR    Line:61   Can't open file  !!!
2023-11-14 13:16:49 Main.py              Send_list_btn_clicked            ERROR    Line:129  Send commands from file  fail!!!
2023-11-14 13:19:25 Main.py              Connect_btn_clicked            INFO     Line:41   visa address: GPIB0::11::INSTR
2023-11-14 13:19:25 Main.py              Connect_btn_clicked            INFO     Line:52   Connect to Instrument successfully
2023-11-14 13:19:29 Main.py              Check_error_btn_clicked        INFO     Line:103  Check error: +0,"No error"

2023-11-14 13:19:58 Main.py              Write_btn_clicked              INFO     Line:66   Send command OUTP 0 to Instrument
2023-11-14 13:20:08 Main.py              Write_btn_clicked              INFO     Line:66   Send command SENS:SWE:POIN 4096 to Instrument
2023-11-14 13:20:15 Main.py              Write_btn_clicked              INFO     Line:66   Send command SENS:CURR:RANG MAX to Instrument
2023-11-14 13:20:22 Main.py              Write_btn_clicked              INFO     Line:66   Send command *CLS to Instrument
2023-11-14 13:20:36 Main.py              Query_btn_clicked              ERROR    Line:87   Can't query command: STAT:PRES
2023-11-14 13:20:44 Main.py              Write_btn_clicked              INFO     Line:66   Send command STAT:PRES to Instrument
2023-11-14 13:20:51 Main.py              Write_btn_clicked              INFO     Line:66   Send command *SRE 0 to Instrument
2023-11-14 13:20:58 Main.py              Write_btn_clicked              INFO     Line:66   Send command *ESE 0 to Instrument
2023-11-14 13:21:06 Main.py              Check_error_btn_clicked        INFO     Line:103  Check error: -420,"Query UNTERMINATED"

2023-11-14 13:21:11 Main.py              Check_error_btn_clicked        INFO     Line:103  Check error: +0,"No error"

2023-11-14 13:21:27 Main.py              Write_btn_clicked              INFO     Line:66   Send command OUTP 1 to Instrument
2023-11-14 13:21:34 Main.py              Write_btn_clicked              INFO     Line:66   Send command VOLT 3.9 to Instrument
2023-11-14 13:21:41 Main.py              Write_btn_clicked              INFO     Line:66   Send command SENS:SWE:POIN 4096 to Instrument
2023-11-14 13:21:49 Main.py              Write_btn_clicked              INFO     Line:66   Send command SENS:CURR:RANG MAX to Instrument
2023-11-14 13:21:59 Main.py              Write_btn_clicked              INFO     Line:66   Send command *CLS to Instrument
2023-11-14 13:22:08 Main.py              Write_btn_clicked              INFO     Line:66   Send command STAT:PRES to Instrument
2023-11-14 13:22:13 Main.py              Write_btn_clicked              INFO     Line:66   Send command *SRE 0 to Instrument
2023-11-14 13:22:18 Main.py              Write_btn_clicked              INFO     Line:66   Send command *ESE 0 to Instrument
2023-11-14 13:22:38 Main.py              Check_error_btn_clicked        INFO     Line:103  Check error: +0,"No error"

2023-11-14 13:22:40 Main.py              Clear_btn_clicked              INFO     Line:108  Clear output screen.
2023-11-14 13:22:52 Main.py              Query_btn_clicked              INFO     Line:91   Send command SYST:ERR? to Instrument
2023-11-14 13:22:52 Main.py              Query_btn_clicked              INFO     Line:94   Get respond: +0,"No error"

2023-11-14 13:24:10 Model.py             Write_commands_from_file       ERROR    Line:61   Can't open file  !!!
2023-11-14 13:24:10 Main.py              Send_list_btn_clicked            ERROR    Line:129  Send commands from file  fail!!!
2023-11-14 13:24:42 Model.py             Write_commands_from_file       INFO     Line:46   Open file <_io.TextIOWrapper name='F:/Mike/Common/Control_Equiment/test.txt' mode='r' encoding='cp1252'> successful.
2023-11-14 13:28:53 Main.py              Connect_btn_clicked            INFO     Line:41   visa address: GPIB0::11::INSTR
2023-11-14 13:28:53 Main.py              Connect_btn_clicked            INFO     Line:52   Connect to Instrument successfully
2023-11-14 13:28:56 Main.py              Check_error_btn_clicked        INFO     Line:103  Check error: +0,"No error"

2023-11-14 13:29:12 Model.py             Write_commands_from_file       INFO     Line:46   Open file <_io.TextIOWrapper name='F:/Mike/Common/Control_Equiment/test.txt' mode='r' encoding='cp1252'> successful.
2023-11-14 13:29:12 Model.py             Write_commands_from_file       INFO     Line:57   Send command SYST:ERR?
 successfull
2023-11-14 13:29:13 Model.py             Write_commands_from_file       INFO     Line:57   Send command *IDN? successfull
2023-11-14 13:29:14 Main.py              Send_list_btn_clicked            INFO     Line:127  Send commands from file F:/Mike/Common/Control_Equiment/test.txt success
